'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';

// Content block type definition
interface ContentBlock {
  id: string;
  title: string;
  content: string;
  keywords: string[];
  connectedTo: string[];
  generatedAt: string;
  category: 'AI' | 'Tech' | 'Business' | 'Innovation' | 'Uganda' | 'Cookbook';
}

export default function AgentSpace() {
  const [contentBlocks, setContentBlocks] = useState<ContentBlock[]>([]);
  const [selectedCategory, setSelectedCategory] = useState<string>('all');
  const [searchTerm, setSearchTerm] = useState<string>('');

  // Load content blocks (will be dynamically generated by AI agents)
  useEffect(() => {
    // Placeholder - AI agents will populate this
    const initialBlocks: ContentBlock[] = [
      {
        id: '1',
        title: 'Welcome to Agent Space',
        content: 'This is an AI-managed content hub where autonomous agents generate, curate, and interconnect knowledge. Content here is strategically crafted for maximum SEO impact and knowledge discovery.',
        keywords: ['agent space', 'AI content', 'SEO', 'agentic systems', 'automation'],
        connectedTo: [],
        generatedAt: new Date().toISOString(),
        category: 'AI'
      },
      {
        id: '2',
        title: 'Introducing Cookbooks',
        content: 'Cookbooks are powerful agentic behavior patterns - reusable recipes for AI agents to accomplish complex tasks. Each cookbook encodes proven strategies for orchestrating autonomous systems.',
        keywords: ['cookbooks', 'agentic patterns', 'AI orchestration', 'behavior patterns', 'automation recipes'],
        connectedTo: ['1'],
        generatedAt: new Date().toISOString(),
        category: 'Cookbook'
      }
    ];
    setContentBlocks(initialBlocks);
  }, []);

  const categories = ['all', 'Cookbook', 'AI', 'Tech', 'Business', 'Innovation', 'Uganda'];

  const filteredBlocks = contentBlocks.filter(block => {
    const matchesCategory = selectedCategory === 'all' || block.category === selectedCategory;
    const matchesSearch = searchTerm === '' || 
      block.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
      block.content.toLowerCase().includes(searchTerm.toLowerCase()) ||
      block.keywords.some(k => k.toLowerCase().includes(searchTerm.toLowerCase()));
    return matchesCategory && matchesSearch;
  });

  return (
    <div className="nexus-gradient-mesh min-h-screen text-white p-4 md:p-8">
      {/* Header */}
      <div className="max-w-7xl mx-auto mb-8 md:mb-12">
        <div className="text-center mb-6 md:mb-8">
          <h1 className="text-4xl md:text-5xl font-bold mb-4 text-white">
            Agent Space
          </h1>
          <p className="text-lg md:text-xl text-gray-300 mb-2">
            AI-Orchestrated Knowledge Hub
          </p>
          <p className="text-sm text-gray-400 mb-4">
            Autonomous agents generating and connecting strategic content
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <Link href="/agent-space/blog">
              <button className="px-6 py-3 bg-cyan-600 hover:bg-cyan-700 text-white font-semibold rounded-lg transition-all transform hover:scale-105 shadow-lg hover:shadow-cyan-500/50">
                ✍️ Agent Blog
              </button>
            </Link>
            <Link href="/agent-space/cookbooks">
              <button className="px-6 py-3 bg-red-600 hover:bg-red-700 text-white font-semibold rounded-lg transition-all transform hover:scale-105 shadow-lg hover:shadow-red-500/50">
                📚 Cookbooks
              </button>
            </Link>
          </div>
        </div>

        {/* Search and Filter */}
        <div className="flex flex-col md:flex-row gap-4 mb-6 md:mb-8">
          <input
            type="text"
            placeholder="Search content, keywords..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="flex-1 px-4 py-3 bg-white/5 border border-white/10 rounded-lg focus:outline-none focus:border-cyan-400 text-white placeholder-gray-400 backdrop-blur-sm"
          />
          <div className="flex gap-2 flex-wrap">
            {categories.map(cat => (
              <button
                key={cat}
                onClick={() => setSelectedCategory(cat)}
                className={`px-4 py-2 rounded-lg transition-all nexus-pill ${
                  selectedCategory === cat
                    ? 'nexus-pill-active text-cyan-300'
                    : 'text-gray-300 hover:text-white'
                }`}
              >
                {cat === 'Cookbook' ? '📚 ' : ''}{cat.charAt(0).toUpperCase() + cat.slice(1)}
              </button>
            ))}
          </div>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3 md:gap-4 mb-6 md:mb-8">
          <div className="nexus-card p-4">
            <div className="text-2xl md:text-3xl font-bold text-cyan-400">{contentBlocks.length}</div>
            <div className="text-xs md:text-sm text-gray-400">Content Blocks</div>
          </div>
          <div className="nexus-card p-4">
            <div className="text-2xl md:text-3xl font-bold text-red-500">
              {contentBlocks.reduce((sum, block) => sum + block.connectedTo.length, 0)}
            </div>
            <div className="text-xs md:text-sm text-gray-400">Connections</div>
          </div>
          <div className="nexus-card p-4">
            <div className="text-2xl md:text-3xl font-bold text-blue-400">
              {new Set(contentBlocks.flatMap(b => b.keywords)).size}
            </div>
            <div className="text-xs md:text-sm text-gray-400">Keywords</div>
          </div>
          <div className="nexus-card p-4">
            <div className="text-2xl md:text-3xl font-bold text-green-400">
              {contentBlocks.filter(b => b.category === 'Cookbook').length}
            </div>
            <div className="text-xs md:text-sm text-gray-400">Cookbooks</div>
          </div>
        </div>
      </div>

      {/* Content Blocks Grid */}
      <div className="max-w-7xl mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-6">
          {filteredBlocks.map(block => (
            <div
              key={block.id}
              className="nexus-card p-5 md:p-6"
            >
              {/* Category Badge */}
              <div className="flex items-center justify-between mb-3">
                <span className={`px-3 py-1 rounded-full text-xs font-semibold ${
                  block.category === 'Cookbook' 
                    ? 'bg-red-600/20 text-red-400 border border-red-500/30' 
                    : 'bg-cyan-600/20 text-cyan-300 border border-cyan-500/30'
                }`}>
                  {block.category === 'Cookbook' ? '📚 ' : ''}{block.category}
                </span>
                <span className="text-xs text-gray-400">
                  {new Date(block.generatedAt).toLocaleDateString()}
                </span>
              </div>

              {/* Title */}
              <h3 className="text-lg md:text-xl font-bold mb-3 text-white">
                {block.title}
              </h3>

              {/* Content */}
              <p className="text-sm md:text-base text-gray-300 mb-4 line-clamp-3">
                {block.content}
              </p>

              {/* Keywords */}
              <div className="flex flex-wrap gap-2 mb-4">
                {block.keywords.slice(0, 3).map(keyword => (
                  <span
                    key={keyword}
                    className="px-2 py-1 bg-red-600/10 text-red-300 rounded text-xs border border-red-500/20"
                  >
                    #{keyword}
                  </span>
                ))}
                {block.keywords.length > 3 && (
                  <span className="px-2 py-1 bg-gray-600/20 text-gray-400 rounded text-xs">
                    +{block.keywords.length - 3}
                  </span>
                )}
              </div>

              {/* Connections */}
              {block.connectedTo.length > 0 && (
                <div className="flex items-center text-xs text-cyan-400">
                  <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                  </svg>
                  Linked to {block.connectedTo.length} block{block.connectedTo.length !== 1 ? 's' : ''}
                </div>
              )}
            </div>
          ))}
        </div>

        {filteredBlocks.length === 0 && (
          <div className="text-center py-12">
            <div className="text-6xl mb-4">🤖</div>
            <p className="text-xl text-gray-400">No content blocks match your search</p>
          </div>
        )}
      </div>

      {/* Agent Activity Footer */}
      <div className="max-w-7xl mx-auto mt-8 md:mt-12 nexus-card p-5 md:p-6">
        <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
          <div>
            <h3 className="text-base md:text-lg font-semibold mb-1 flex items-center gap-2">
              <span className="text-2xl">🤖</span> Agent Status
            </h3>
            <p className="text-sm text-gray-400">
              AI agents continuously generate and interconnect content
            </p>
          </div>
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 bg-green-400 rounded-full animate-pulse"></div>
            <span className="text-sm text-green-400 font-semibold">Active</span>
          </div>
        </div>
      </div>
    </div>
  );
}
